server:
  port: 9527

eureka:

  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka1.com:7001/eureka
  instance:
    instance-id: cloud-gateway-service
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      # 路由si(集合)
      routes:
        # id唯一标识
        - id: consumer-service-route
          # 路由服务地址
          uri: lb://cloud-payment-service
          # 断言
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=name,changhao
  application:
    name: cloud-gateway




