server:
  port: 8001

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://eureka1.com:7001/eureka
#      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
      # 集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: hystrix-payment-8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
spring:
  application:
    name: hystrix-payment

# 配置熔断策略：
hystrix:
  command:
    default:
      circuitBreaker:
        forceOpen: false # 强制打开熔断器 默认false关闭的
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
        sleepWindowInMilliseconds: 5000  # 熔断后休眠时长，默认值5秒
        requestVolumeThreshold: 20  # 熔断触发最小请求次数，默认值是20
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000  # 熔断超时设置，默认为1秒
#暴露全部监控信息,可以只填写hystrix.stream，也可以暴露全部 * ，注意在yml文件中特殊符号需要加引号
management:
  endpoints:
    web:
      exposure:
        include: '*'