server:
  port: 3344

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /ingin
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mixpplus/cloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          default-label: master
      #          search-paths:
#            - springcloud-config
      ####读取分支


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://eureka1.com:7001/eureka
      #      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
      # 集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-server
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
# 暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        # 暴露触发消息总线的地址
        include: bus-refresh

